---
title: "Carla M. Sette, PhD"
output: 
  html_document:
    toc: FALSE
---

<p>&nbsp;</p>
#### I am a computational ecologist who specializes in mechanistic modeling and statistical analysis of complex biological systems and large datasets. I am excited to transition from academic research to Data Science.
I have over 9 years of experience in experimental design, hypothesis testing, and mathematical modeling of various biological systems. I have done a little bit of everything in my biology career - I have worked in sterile biotech labs  and in the Amazon. I've studied disease ecology, thermal ecology, climate change, and game theory. I have also trained in STEM pedagogy and science communication, presented my research at scientific conferences, and published in peer-reviewed journals. 
[Learn more about me](./about-me.html)

<p>&nbsp;</p>
## Projects
### [solveSimplex](https://cmsette.shinyapps.io/solvesimplex/)
**solveSimplex** is an evolutionary game theory solver in R for single-population games with 2-5 strategies. 

This code solves for all internal and face equilibria and classifies the equilibrium types (source, saddle, sink). It also identifies games and strategies exhibiting strict-sense intransitivity, negative frequency-dependence (apostasis), and positive frequency-dependence (anti-apostasis). Analysis of face games allows for better understanding of equilibrium dynamics in the system and invasion pathways for individual strategies. 

I developed this code to study the mathematical properties of stable systems of competitors (and the corresponding biological conditions).

* [solveSimplex shiny app](https://cmsette.shinyapps.io/solvesimplex/)
* [Guide to using solveSimplex](./solveSimplex-guide.html)
* [Source code on GitHub](https://github.com/cmsette/solveSimplex)

